# Generated by Django 3.1.7 on 2021-03-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210325_0951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salts',
        ),
    ]
